### ISSUE TITLE
Crouch insta resetting and Radial menu limited?

### ISSUE THREAD

**Issue by CharlesDaHefe** [Project-Sloth/ps-walkingstyle#6]
Crouching just instantly gets undone when trying to crouch. Ive also added serveral walkstyles from rpemotes and they work great but i cant seem to add past 7 pages on the radial f1 wheel? It just goes to a blank wheel after the 7th but ive added 4 more beyond that. Is there anyway to acheive more then 7 pages? (each page has 10 walkstyles on them)

**Comment by AndrewParker7894** [comment]
any fix for the crouching issue????
